theme: minima
title: JAYMAC BLOGS
author: GitHub User
email: yjaymac@domain.com
description: > # this means to ignore newlines until "baseurl:"
  HOME OF ALL GEARS..

# social links
twitter_username: jaymacautomotives # DO NOT include the @ character, or else the build will fail!
github_username:  mayeku-caleb # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
